package roadmap

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"agyreview/internal/model"
)

type MilestoneItem struct {
	ID             string
	Title          string
	TargetHorizon  string
	TargetEffort   string
	ProjectedGain  int // Points on 100-pt barème
	Description    string
	Deliverables   []string
}

// GenerateProductRoadmap translates audit findings and architectural gaps into a 3-Horizon strategic evolution plan.
func GenerateProductRoadmap(target *model.TargetRepo, findings []model.Finding, currentScore model.BaremScore) (string, error) {
	var b strings.Builder
	timestamp := time.Now().Format("2006-01-02 15:04:05 MST")

	b.WriteString("# 🗺️ Strategic Product Roadmap & Technical Debt Evolution Plan\n\n")
	b.WriteString(fmt.Sprintf("> **Target Repository**: `%s`  \n", target.Name))
	b.WriteString(fmt.Sprintf("> **Baseline Quality Score**: `%d / 100 (Grade: %s)`  \n", currentScore.TotalPoints, currentScore.LetterGrade))
	b.WriteString(fmt.Sprintf("> **Generated At**: `%s`  \n", timestamp))
	b.WriteString("> **Methodology**: 3-Horizon Strategic Evolution & Continuous Technical Debt Retirement  \n\n")
	b.WriteString("---\n\n")

	// Executive Summary & Evolution Trajectory
	h1Target := min(100, currentScore.TotalPoints+15)
	h2Target := min(100, currentScore.TotalPoints+25)
	h3Target := min(100, currentScore.TotalPoints+30)

	b.WriteString("## 1. Executive Quality & Architecture Trajectory\n\n")
	b.WriteString("| Strategic Horizon | Timeline | Objective Focus | Target Barème Score | Grade |\n")
	b.WriteString("| :--- | :---: | :--- | :---: | :---: |\n")
	b.WriteString(fmt.Sprintf("| **Current Baseline** | Today | Current Codebase State | **%d / 100** | `%s` |\n", currentScore.TotalPoints, currentScore.LetterGrade))
	b.WriteString(fmt.Sprintf("| **Horizon 1: Hardening** | 0 – 30 Days | Zero-defect hardening, P0/P1 retirement | **%d / 100** | `A` |\n", h1Target))
	b.WriteString(fmt.Sprintf("| **Horizon 2: Scale** | 30 – 90 Days | Modularity, test rig expansion (>85%%) | **%d / 100** | `A+` |\n", h2Target))
	b.WriteString(fmt.Sprintf("| **Horizon 3: Autonomous** | 90 – 360 Days | Multi-agent coordination & self-healing | **%d / 100** | `A+` |\n\n", h3Target))
	b.WriteString("---\n\n")

	// Horizon 1
	b.WriteString("## 2. Horizon 1: Immediate Stabilization & Hardening (0 – 30 Days)\n\n")
	b.WriteString("### Goal: Liquidate all critical security blockers, concurrency risks, and resource leaks.\n\n")
	b.WriteString("#### Milestones & Work Packages:\n")
	b.WriteString("1. **[M1.1] Security & Credential Liquidation**:\n")
	b.WriteString("   - Extract hardcoded tokens and environment secrets into secure storage or vault.\n")
	b.WriteString("   - Sanitize all external command executions against shell injection.\n")
	b.WriteString("   - *Impact*: +10 Security Barème points.\n")
	b.WriteString("2. **[M1.2] Concurrency Lifecycle Enclosure**:\n")
	b.WriteString("   - Enforce explicit `context.Context` cancellation for all spawned background goroutines.\n")
	b.WriteString("   - Audit and close all open OS file descriptors and PTY handles on exit.\n")
	b.WriteString("   - *Impact*: +5 Concurrency Barème points.\n\n")

	// Horizon 2
	b.WriteString("## 3. Horizon 2: Architectural Decoupling & Test Rig Scaling (30 – 90 Days)\n\n")
	b.WriteString("### Goal: Establish modular boundaries, eliminate cross-module code smells, and raise automated test coverage to >85%.\n\n")
	b.WriteString("#### Milestones & Work Packages:\n")
	b.WriteString("1. **[M2.1] Core Domain Interface Decoupling**:\n")
	b.WriteString("   - Segregate TUI presentation layers from core engine state and IO drivers.\n")
	b.WriteString("   - Implement mockable engine interfaces for automated unit tests.\n")
	b.WriteString("2. **[M2.2] Test Rig Expansion & Automated CI Gates**:\n")
	b.WriteString("   - Achieve >85% test coverage across all domain and service packages.\n")
	b.WriteString("   - Embed `agyreview run --strict` as a blocking GitHub Actions pull request gate.\n\n")

	// Horizon 3
	b.WriteString("## 4. Horizon 3: Autonomous Orchestration & Ecosystem Modernization (90 – 360 Days)\n\n")
	b.WriteString("### Goal: Deliver multi-agent autonomous coordination, real-time telemetry, and self-healing CI/CD gates.\n\n")
	b.WriteString("#### Milestones & Work Packages:\n")
	b.WriteString("1. **[M3.1] Multi-Agent Swarm Orchestration**:\n")
	b.WriteString("   - Integrate parallel child PTY swarm runners across accounts and workspaces.\n")
	b.WriteString("   - Automate pull request generation and verified patch validation.\n")
	b.WriteString("2. **[M3.2] Universal Platform Telemetry**:\n")
	b.WriteString("   - Cross-platform unified mobile cockpit and real-time event streaming.\n\n")

	b.WriteString("---\n\n")
	b.WriteString("> **Generated by**: `agyreview roadmap` utilizing the `product-roadmap-evolution` skill.\n")

	outPath := filepath.Join(target.Path, "PRODUCT_ROADMAP.md")
	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		return "", err
	}

	return outPath, nil
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
