global using AgyTui.Core.Interfaces;
global using AgyTui.Core.Models;
global using AgyTui.Core.Registries;
global using AgyTui.Infrastructure;
global using AgyTui.Infrastructure.Common;
global using AgyTui.Infrastructure.Integrations.Ai;
global using AgyTui.Infrastructure.Integrations.Aws;
global using AgyTui.Infrastructure.Integrations.Docker;
global using AgyTui.Infrastructure.Integrations.DotNet;
global using AgyTui.Infrastructure.Integrations.Git;
global using AgyTui.Infrastructure.Integrations.Obsidian;
global using AgyTui.Infrastructure.Integrations.Sys;
global using AgyTui.Infrastructure.Integrations.AgyClient;
global using AgyTui.Infrastructure.Persistence.Learning;
global using AgyTui.UI.Core.Common;
global using AgyTui.UI.Core.Layouts;
global using AgyTui.UI.Core.Navigation;
global using AgyTui.UI.Screens.Career;
global using AgyTui.UI.Screens.Git;
global using AgyTui.UI.Screens.Ide;
global using AgyTui.UI.Screens.Learn;
global using AgyTui.UI.Screens.Quizzes;
global using Spectre.Console;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Text;
global using Helpers = AgyTui.Infrastructure.Common;
global using SshHelper = AgyTui.UI.Screens.SysNet.SshConsoleView;
global using SystemHelper = AgyTui.Infrastructure.Common.SystemConsoleView;
